"""empty message

Revision ID: 79024bd9dc08
Revises: 512d528281d3
Create Date: 2019-10-22 17:02:07.489697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79024bd9dc08'
down_revision = '512d528281d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coments_pkey')
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
