"""empty message

Revision ID: 99e8e6ae9eff
Revises: f43f1f4baea0
Create Date: 2019-10-21 20:37:15.389579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e8e6ae9eff'
down_revision = 'f43f1f4baea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reviews', sa.Column('pitch', sa.String(), nullable=True))
    op.drop_column('reviews', 'pitch_review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pitch_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'pitch')
    op.drop_table('coments')
    # ### end Alembic commands ###
